package net.forger.dreamsofdivinity.network;

import net.neoforged.neoforge.registries.NeoForgeRegistries;
import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.network.handling.IPayloadContext;
import net.neoforged.neoforge.network.PacketDistributor;
import net.neoforged.neoforge.event.entity.player.PlayerEvent;
import net.neoforged.neoforge.common.util.INBTSerializable;
import net.neoforged.neoforge.attachment.AttachmentType;
import net.neoforged.fml.event.lifecycle.FMLCommonSetupEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;

import net.minecraft.world.entity.Entity;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.network.protocol.common.custom.CustomPacketPayload;
import net.minecraft.network.protocol.PacketFlow;
import net.minecraft.network.codec.StreamCodec;
import net.minecraft.network.chat.Component;
import net.minecraft.network.RegistryFriendlyByteBuf;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.core.HolderLookup;

import net.forger.dreamsofdivinity.DreamsOfDivinityMod;

import java.util.function.Supplier;

@EventBusSubscriber(bus = EventBusSubscriber.Bus.MOD)
public class DreamsOfDivinityModVariables {
	public static final DeferredRegister<AttachmentType<?>> ATTACHMENT_TYPES = DeferredRegister.create(NeoForgeRegistries.Keys.ATTACHMENT_TYPES, DreamsOfDivinityMod.MODID);
	public static final Supplier<AttachmentType<PlayerVariables>> PLAYER_VARIABLES = ATTACHMENT_TYPES.register("player_variables", () -> AttachmentType.serializable(() -> new PlayerVariables()).build());

	@SubscribeEvent
	public static void init(FMLCommonSetupEvent event) {
		DreamsOfDivinityMod.addNetworkMessage(PlayerVariablesSyncMessage.TYPE, PlayerVariablesSyncMessage.STREAM_CODEC, PlayerVariablesSyncMessage::handleData);
	}

	@EventBusSubscriber
	public static class EventBusVariableHandlers {
		@SubscribeEvent
		public static void onPlayerLoggedInSyncPlayerVariables(PlayerEvent.PlayerLoggedInEvent event) {
			if (event.getEntity() instanceof ServerPlayer player)
				player.getData(PLAYER_VARIABLES).syncPlayerVariables(event.getEntity());
		}

		@SubscribeEvent
		public static void onPlayerRespawnedSyncPlayerVariables(PlayerEvent.PlayerRespawnEvent event) {
			if (event.getEntity() instanceof ServerPlayer player)
				player.getData(PLAYER_VARIABLES).syncPlayerVariables(event.getEntity());
		}

		@SubscribeEvent
		public static void onPlayerChangedDimensionSyncPlayerVariables(PlayerEvent.PlayerChangedDimensionEvent event) {
			if (event.getEntity() instanceof ServerPlayer player)
				player.getData(PLAYER_VARIABLES).syncPlayerVariables(event.getEntity());
		}

		@SubscribeEvent
		public static void clonePlayer(PlayerEvent.Clone event) {
			PlayerVariables original = event.getOriginal().getData(PLAYER_VARIABLES);
			PlayerVariables clone = new PlayerVariables();
			clone.mana = original.mana;
			clone.maxmana = original.maxmana;
			clone.magicpower = original.magicpower;
			clone.magicpower1 = original.magicpower1;
			clone.magicpower2 = original.magicpower2;
			clone.magicpower3 = original.magicpower3;
			clone.magicpower4 = original.magicpower4;
			clone.magicpower5 = original.magicpower5;
			clone.magicpower6 = original.magicpower6;
			clone.health = original.health;
			clone.maxhealth = original.maxhealth;
			clone.damage = original.damage;
			clone.armor = original.armor;
			clone.magicspeed = original.magicspeed;
			clone.magicspeed1 = original.magicspeed1;
			clone.magicspeed2 = original.magicspeed2;
			clone.magicspeed3 = original.magicspeed3;
			clone.magicspeed4 = original.magicspeed4;
			clone.magicspeed5 = original.magicspeed5;
			clone.magicspeed6 = original.magicspeed6;
			clone.magicsize = original.magicsize;
			clone.magicsize1 = original.magicsize1;
			clone.magicsize2 = original.magicsize2;
			clone.magicsize3 = original.magicsize3;
			clone.magicsize4 = original.magicsize4;
			clone.magicsize5 = original.magicsize5;
			clone.magicsize6 = original.magicsize6;
			clone.overheat = original.overheat;
			clone.overheat1 = original.overheat1;
			clone.overheat2 = original.overheat2;
			clone.overheat3 = original.overheat3;
			clone.overheat4 = original.overheat4;
			clone.overheat5 = original.overheat5;
			clone.overheat6 = original.overheat6;
			clone.magicstyle = original.magicstyle;
			clone.magicstyle1 = original.magicstyle1;
			clone.magicstyle2 = original.magicstyle2;
			clone.magicstyle3 = original.magicstyle3;
			clone.magicstyle4 = original.magicstyle4;
			clone.magicstyle5 = original.magicstyle5;
			clone.magicstyle6 = original.magicstyle6;
			clone.MagicMastery = original.MagicMastery;
			clone.firemagic = original.firemagic;
			clone.watermagic = original.watermagic;
			clone.UnlockPoints = original.UnlockPoints;
			clone.spell = original.spell;
			clone.Piercing = original.Piercing;
			clone.Piercing1 = original.Piercing1;
			clone.Piercing2 = original.Piercing2;
			clone.Piercing3 = original.Piercing3;
			clone.Piercing4 = original.Piercing4;
			clone.Piercing5 = original.Piercing5;
			clone.Piercing6 = original.Piercing6;
			clone.Tracking = original.Tracking;
			clone.Tracking1 = original.Tracking1;
			clone.Tracking2 = original.Tracking2;
			clone.Tracking3 = original.Tracking3;
			clone.Tracking4 = original.Tracking4;
			clone.Tracking5 = original.Tracking5;
			clone.Tracking6 = original.Tracking6;
			clone.MagicShape = original.MagicShape;
			clone.MagicShape1 = original.MagicShape1;
			clone.MagicShape2 = original.MagicShape2;
			clone.MagicShape3 = original.MagicShape3;
			clone.MagicShape4 = original.MagicShape4;
			clone.MagicShape5 = original.MagicShape5;
			clone.MagicShape6 = original.MagicShape6;
			clone.MagicFollowSetting = original.MagicFollowSetting;
			clone.MagicFollowSetting1 = original.MagicFollowSetting1;
			clone.MagicFollowSetting2 = original.MagicFollowSetting2;
			clone.MagicFollowSetting3 = original.MagicFollowSetting3;
			clone.MagicFollowSetting4 = original.MagicFollowSetting4;
			clone.MagicFollowSetting5 = original.MagicFollowSetting5;
			clone.MagicFollowSetting6 = original.MagicFollowSetting6;
			clone.SelectionMultiplier = original.SelectionMultiplier;
			clone.MagicDuration = original.MagicDuration;
			clone.MagicDuration1 = original.MagicDuration1;
			clone.MagicDuration2 = original.MagicDuration2;
			clone.MagicDuration3 = original.MagicDuration3;
			clone.MagicDuration4 = original.MagicDuration4;
			clone.MagicDuration5 = original.MagicDuration5;
			clone.MagicDuration6 = original.MagicDuration6;
			clone.MultiCast = original.MultiCast;
			clone.MultiCast1 = original.MultiCast1;
			clone.MultiCast2 = original.MultiCast2;
			clone.MultiCast3 = original.MultiCast3;
			clone.MultiCast4 = original.MultiCast4;
			clone.MultiCast5 = original.MultiCast5;
			clone.MultiCast6 = original.MultiCast6;
			clone.magicaffinity = original.magicaffinity;
			clone.magicaffinityselected = original.magicaffinityselected;
			clone.magicaffinity1 = original.magicaffinity1;
			clone.magicaffinity2 = original.magicaffinity2;
			clone.magicaffinity3 = original.magicaffinity3;
			clone.magicaffinity4 = original.magicaffinity4;
			clone.magicaffinity5 = original.magicaffinity5;
			clone.magicaffinity6 = original.magicaffinity6;
			clone.Stamina = original.Stamina;
			clone.MaxStamina = original.MaxStamina;
			clone.Dash = original.Dash;
			clone.Dash2 = original.Dash2;
			clone.Dash3 = original.Dash3;
			clone.Dash4 = original.Dash4;
			clone.Sprint = original.Sprint;
			clone.MagicCost = original.MagicCost;
			clone.MagicCost2 = original.MagicCost2;
			clone.notenoughmana = original.notenoughmana;
			clone.wallrunning = original.wallrunning;
			clone.wallside = original.wallside;
			clone.immunity = original.immunity;
			clone.immunitytrue = original.immunitytrue;
			clone.runningwall = original.runningwall;
			clone.falling = original.falling;
			clone.maxfall = original.maxfall;
			clone.maxfallingbonus = original.maxfallingbonus;
			clone.magicdirection = original.magicdirection;
			clone.magicdirection1 = original.magicdirection1;
			clone.magicdirection2 = original.magicdirection2;
			clone.magicdirection3 = original.magicdirection3;
			clone.magicdirection4 = original.magicdirection4;
			clone.magicdirection5 = original.magicdirection5;
			clone.magicdirection6 = original.magicdirection6;
			clone.castingoffset = original.castingoffset;
			clone.castingoffset1 = original.castingoffset1;
			clone.castingoffset2 = original.castingoffset2;
			clone.castingoffset3 = original.castingoffset3;
			clone.castingoffset4 = original.castingoffset4;
			clone.castingoffset5 = original.castingoffset5;
			clone.castingoffset6 = original.castingoffset6;
			clone.guidedmagic = original.guidedmagic;
			clone.guidedmagic1 = original.guidedmagic1;
			clone.guidedmagic2 = original.guidedmagic2;
			clone.guidedmagic3 = original.guidedmagic3;
			clone.guidedmagic4 = original.guidedmagic4;
			clone.guidedmagic5 = original.guidedmagic5;
			clone.guidedmagic6 = original.guidedmagic6;
			clone.areacoverage = original.areacoverage;
			clone.areacoverage1 = original.areacoverage1;
			clone.areacoverage2 = original.areacoverage2;
			clone.areacoverage3 = original.areacoverage3;
			clone.areacoverage4 = original.areacoverage4;
			clone.areacoverage5 = original.areacoverage5;
			clone.areacoverage6 = original.areacoverage6;
			clone.dash5 = original.dash5;
			clone.fire = original.fire;
			clone.fire1 = original.fire1;
			clone.fire2 = original.fire2;
			clone.fire3 = original.fire3;
			clone.fire4 = original.fire4;
			clone.fire5 = original.fire5;
			clone.fire6 = original.fire6;
			clone.water = original.water;
			clone.water1 = original.water1;
			clone.water2 = original.water2;
			clone.water3 = original.water3;
			clone.water4 = original.water4;
			clone.water5 = original.water5;
			clone.water6 = original.water6;
			clone.gravity = original.gravity;
			clone.gravity1 = original.gravity1;
			clone.gravity2 = original.gravity2;
			clone.gravity3 = original.gravity3;
			clone.gravity4 = original.gravity4;
			clone.gravity5 = original.gravity5;
			clone.gravity6 = original.gravity6;
			clone.basespeed = original.basespeed;
			clone.joinworldlock = original.joinworldlock;
			clone.party = original.party;
			clone.partyinvite = original.partyinvite;
			clone.immunityinvited = original.immunityinvited;
			clone.immunityinvite = original.immunityinvite;
			clone.partyrank = original.partyrank;
			clone.partyname = original.partyname;
			clone.magicname = original.magicname;
			clone.magicname1 = original.magicname1;
			clone.magicname2 = original.magicname2;
			clone.magicname3 = original.magicname3;
			clone.magicname4 = original.magicname4;
			clone.magicname5 = original.magicname5;
			clone.magicname6 = original.magicname6;
			clone.MagicAttribute = original.MagicAttribute;
			if (!event.isWasDeath()) {
				clone.chargeup = original.chargeup;
				clone.movementforward = original.movementforward;
				clone.movementbackward = original.movementbackward;
				clone.movementright = original.movementright;
				clone.movementleft = original.movementleft;
				clone.movementup = original.movementup;
				clone.movementenhance = original.movementenhance;
			}
			event.getEntity().setData(PLAYER_VARIABLES, clone);
		}
	}

	public static class PlayerVariables implements INBTSerializable<CompoundTag> {
		public double mana = 0;
		public double maxmana = 200.0;
		public double magicpower = 0;
		public double magicpower1 = 0;
		public double magicpower2 = 0;
		public double magicpower3 = 0;
		public double magicpower4 = 0;
		public double magicpower5 = 0;
		public double magicpower6 = 0;
		public double health = 0;
		public double maxhealth = 0;
		public double damage = 0;
		public double armor = 0;
		public double magicspeed = 0;
		public double magicspeed1 = 0;
		public double magicspeed2 = 0;
		public double magicspeed3 = 0;
		public double magicspeed4 = 0;
		public double magicspeed5 = 0;
		public double magicspeed6 = 0;
		public double magicsize = 1.0;
		public double magicsize1 = 1.0;
		public double magicsize2 = 1.0;
		public double magicsize3 = 1.0;
		public double magicsize4 = 1.0;
		public double magicsize5 = 1.0;
		public double magicsize6 = 1.0;
		public double overheat = 40.0;
		public double overheat1 = 40.0;
		public double overheat2 = 40.0;
		public double overheat3 = 40.0;
		public double overheat4 = 40.0;
		public double overheat5 = 40.0;
		public double overheat6 = 40.0;
		public double magicstyle = 0;
		public double magicstyle1 = 0;
		public double magicstyle2 = 0;
		public double magicstyle3 = 0;
		public double magicstyle4 = 0;
		public double magicstyle5 = 0;
		public double magicstyle6 = 0;
		public double MagicMastery = 0;
		public boolean firemagic = false;
		public boolean watermagic = false;
		public double UnlockPoints = 10.0;
		public double spell = 0;
		public double Piercing = 0;
		public double Piercing1 = 0;
		public double Piercing2 = 0;
		public double Piercing3 = 0;
		public double Piercing4 = 0;
		public double Piercing5 = 0;
		public double Piercing6 = 0;
		public double Tracking = 0;
		public double Tracking1 = 0;
		public double Tracking2 = 0;
		public double Tracking3 = 0;
		public double Tracking4 = 0;
		public double Tracking5 = 0;
		public double Tracking6 = 0;
		public double MagicShape = 1.0;
		public double MagicShape1 = 1.0;
		public double MagicShape2 = 1.0;
		public double MagicShape3 = 1.0;
		public double MagicShape4 = 1.0;
		public double MagicShape5 = 1.0;
		public double MagicShape6 = 1.0;
		public double MagicFollowSetting = 1.0;
		public double MagicFollowSetting1 = 1.0;
		public double MagicFollowSetting2 = 1.0;
		public double MagicFollowSetting3 = 1.0;
		public double MagicFollowSetting4 = 1.0;
		public double MagicFollowSetting5 = 1.0;
		public double MagicFollowSetting6 = 1.0;
		public double SelectionMultiplier = 1.0;
		public double MagicDuration = 1.0;
		public double MagicDuration1 = 1.0;
		public double MagicDuration2 = 1.0;
		public double MagicDuration3 = 1.0;
		public double MagicDuration4 = 1.0;
		public double MagicDuration5 = 1.0;
		public double MagicDuration6 = 1.0;
		public double MultiCast = 1.0;
		public double MultiCast1 = 1.0;
		public double MultiCast2 = 1.0;
		public double MultiCast3 = 1.0;
		public double MultiCast4 = 1.0;
		public double MultiCast5 = 1.0;
		public double MultiCast6 = 1.0;
		public double magicaffinity = 0;
		public double magicaffinityselected = 0;
		public double magicaffinity1 = 0;
		public double magicaffinity2 = 0;
		public double magicaffinity3 = 0;
		public double magicaffinity4 = 0;
		public double magicaffinity5 = 0;
		public double magicaffinity6 = 0;
		public double Stamina = 0;
		public double MaxStamina = 200.0;
		public double Dash = 0;
		public double Dash2 = 0;
		public double Dash3 = 0;
		public double Dash4 = 0;
		public double Sprint = 0;
		public double MagicCost = 0;
		public double MagicCost2 = 0;
		public boolean chargeup = false;
		public double notenoughmana = 0;
		public double wallrunning = 0;
		public double wallside = 0;
		public double immunity = 0;
		public boolean immunitytrue = false;
		public boolean runningwall = false;
		public double falling = 0;
		public double maxfall = 80.0;
		public double maxfallingbonus = 0;
		public double magicdirection = 1.0;
		public double magicdirection1 = 1.0;
		public double magicdirection2 = 1.0;
		public double magicdirection3 = 1.0;
		public double magicdirection4 = 1.0;
		public double magicdirection5 = 1.0;
		public double magicdirection6 = 1.0;
		public double castingoffset = 1.0;
		public double castingoffset1 = 1.0;
		public double castingoffset2 = 1.0;
		public double castingoffset3 = 1.0;
		public double castingoffset4 = 1.0;
		public double castingoffset5 = 1.0;
		public double castingoffset6 = 1.0;
		public double guidedmagic = 0.0;
		public double guidedmagic1 = 0.0;
		public double guidedmagic2 = 0.0;
		public double guidedmagic3 = 0.0;
		public double guidedmagic4 = 0.0;
		public double guidedmagic5 = 0.0;
		public double guidedmagic6 = 0.0;
		public double areacoverage = 1.0;
		public double areacoverage1 = 1.0;
		public double areacoverage2 = 1.0;
		public double areacoverage3 = 1.0;
		public double areacoverage4 = 1.0;
		public double areacoverage5 = 1.0;
		public double areacoverage6 = 1.0;
		public double dash5 = 0;
		public boolean fire = false;
		public boolean fire1 = false;
		public boolean fire2 = false;
		public boolean fire3 = false;
		public boolean fire4 = false;
		public boolean fire5 = false;
		public boolean fire6 = false;
		public boolean water = false;
		public boolean water1 = false;
		public boolean water2 = false;
		public boolean water3 = false;
		public boolean water4 = false;
		public boolean water5 = false;
		public boolean water6 = false;
		public double gravity = 0;
		public double gravity1 = 0;
		public double gravity2 = 0;
		public double gravity3 = 0;
		public double gravity4 = 0;
		public double gravity5 = 0;
		public double gravity6 = 0;
		public double basespeed = 0;
		public boolean joinworldlock = false;
		public double movementforward = 0;
		public double movementbackward = 0;
		public double movementright = 0;
		public double movementleft = 0;
		public double movementup = 0;
		public double movementenhance = 0;
		public boolean party = false;
		public boolean partyinvite = false;
		public double immunityinvited = 0;
		public double immunityinvite = 0;
		public double partyrank = 0;
		public String partyname = "Party Name?";
		public String magicname = "\"\"";
		public String magicname1 = "\"\"";
		public String magicname2 = "";
		public String magicname3 = "\"\"";
		public String magicname4 = "\"\"";
		public String magicname5 = "\"\"";
		public String magicname6 = "\"\"";
		public String MagicAttribute = "\"\"";

		@Override
		public CompoundTag serializeNBT(HolderLookup.Provider lookupProvider) {
			CompoundTag nbt = new CompoundTag();
			nbt.putDouble("mana", mana);
			nbt.putDouble("maxmana", maxmana);
			nbt.putDouble("magicpower", magicpower);
			nbt.putDouble("magicpower1", magicpower1);
			nbt.putDouble("magicpower2", magicpower2);
			nbt.putDouble("magicpower3", magicpower3);
			nbt.putDouble("magicpower4", magicpower4);
			nbt.putDouble("magicpower5", magicpower5);
			nbt.putDouble("magicpower6", magicpower6);
			nbt.putDouble("health", health);
			nbt.putDouble("maxhealth", maxhealth);
			nbt.putDouble("damage", damage);
			nbt.putDouble("armor", armor);
			nbt.putDouble("magicspeed", magicspeed);
			nbt.putDouble("magicspeed1", magicspeed1);
			nbt.putDouble("magicspeed2", magicspeed2);
			nbt.putDouble("magicspeed3", magicspeed3);
			nbt.putDouble("magicspeed4", magicspeed4);
			nbt.putDouble("magicspeed5", magicspeed5);
			nbt.putDouble("magicspeed6", magicspeed6);
			nbt.putDouble("magicsize", magicsize);
			nbt.putDouble("magicsize1", magicsize1);
			nbt.putDouble("magicsize2", magicsize2);
			nbt.putDouble("magicsize3", magicsize3);
			nbt.putDouble("magicsize4", magicsize4);
			nbt.putDouble("magicsize5", magicsize5);
			nbt.putDouble("magicsize6", magicsize6);
			nbt.putDouble("overheat", overheat);
			nbt.putDouble("overheat1", overheat1);
			nbt.putDouble("overheat2", overheat2);
			nbt.putDouble("overheat3", overheat3);
			nbt.putDouble("overheat4", overheat4);
			nbt.putDouble("overheat5", overheat5);
			nbt.putDouble("overheat6", overheat6);
			nbt.putDouble("magicstyle", magicstyle);
			nbt.putDouble("magicstyle1", magicstyle1);
			nbt.putDouble("magicstyle2", magicstyle2);
			nbt.putDouble("magicstyle3", magicstyle3);
			nbt.putDouble("magicstyle4", magicstyle4);
			nbt.putDouble("magicstyle5", magicstyle5);
			nbt.putDouble("magicstyle6", magicstyle6);
			nbt.putDouble("MagicMastery", MagicMastery);
			nbt.putBoolean("firemagic", firemagic);
			nbt.putBoolean("watermagic", watermagic);
			nbt.putDouble("UnlockPoints", UnlockPoints);
			nbt.putDouble("spell", spell);
			nbt.putDouble("Piercing", Piercing);
			nbt.putDouble("Piercing1", Piercing1);
			nbt.putDouble("Piercing2", Piercing2);
			nbt.putDouble("Piercing3", Piercing3);
			nbt.putDouble("Piercing4", Piercing4);
			nbt.putDouble("Piercing5", Piercing5);
			nbt.putDouble("Piercing6", Piercing6);
			nbt.putDouble("Tracking", Tracking);
			nbt.putDouble("Tracking1", Tracking1);
			nbt.putDouble("Tracking2", Tracking2);
			nbt.putDouble("Tracking3", Tracking3);
			nbt.putDouble("Tracking4", Tracking4);
			nbt.putDouble("Tracking5", Tracking5);
			nbt.putDouble("Tracking6", Tracking6);
			nbt.putDouble("MagicShape", MagicShape);
			nbt.putDouble("MagicShape1", MagicShape1);
			nbt.putDouble("MagicShape2", MagicShape2);
			nbt.putDouble("MagicShape3", MagicShape3);
			nbt.putDouble("MagicShape4", MagicShape4);
			nbt.putDouble("MagicShape5", MagicShape5);
			nbt.putDouble("MagicShape6", MagicShape6);
			nbt.putDouble("MagicFollowSetting", MagicFollowSetting);
			nbt.putDouble("MagicFollowSetting1", MagicFollowSetting1);
			nbt.putDouble("MagicFollowSetting2", MagicFollowSetting2);
			nbt.putDouble("MagicFollowSetting3", MagicFollowSetting3);
			nbt.putDouble("MagicFollowSetting4", MagicFollowSetting4);
			nbt.putDouble("MagicFollowSetting5", MagicFollowSetting5);
			nbt.putDouble("MagicFollowSetting6", MagicFollowSetting6);
			nbt.putDouble("SelectionMultiplier", SelectionMultiplier);
			nbt.putDouble("MagicDuration", MagicDuration);
			nbt.putDouble("MagicDuration1", MagicDuration1);
			nbt.putDouble("MagicDuration2", MagicDuration2);
			nbt.putDouble("MagicDuration3", MagicDuration3);
			nbt.putDouble("MagicDuration4", MagicDuration4);
			nbt.putDouble("MagicDuration5", MagicDuration5);
			nbt.putDouble("MagicDuration6", MagicDuration6);
			nbt.putDouble("MultiCast", MultiCast);
			nbt.putDouble("MultiCast1", MultiCast1);
			nbt.putDouble("MultiCast2", MultiCast2);
			nbt.putDouble("MultiCast3", MultiCast3);
			nbt.putDouble("MultiCast4", MultiCast4);
			nbt.putDouble("MultiCast5", MultiCast5);
			nbt.putDouble("MultiCast6", MultiCast6);
			nbt.putDouble("magicaffinity", magicaffinity);
			nbt.putDouble("magicaffinityselected", magicaffinityselected);
			nbt.putDouble("magicaffinity1", magicaffinity1);
			nbt.putDouble("magicaffinity2", magicaffinity2);
			nbt.putDouble("magicaffinity3", magicaffinity3);
			nbt.putDouble("magicaffinity4", magicaffinity4);
			nbt.putDouble("magicaffinity5", magicaffinity5);
			nbt.putDouble("magicaffinity6", magicaffinity6);
			nbt.putDouble("Stamina", Stamina);
			nbt.putDouble("MaxStamina", MaxStamina);
			nbt.putDouble("Dash", Dash);
			nbt.putDouble("Dash2", Dash2);
			nbt.putDouble("Dash3", Dash3);
			nbt.putDouble("Dash4", Dash4);
			nbt.putDouble("Sprint", Sprint);
			nbt.putDouble("MagicCost", MagicCost);
			nbt.putDouble("MagicCost2", MagicCost2);
			nbt.putBoolean("chargeup", chargeup);
			nbt.putDouble("notenoughmana", notenoughmana);
			nbt.putDouble("wallrunning", wallrunning);
			nbt.putDouble("wallside", wallside);
			nbt.putDouble("immunity", immunity);
			nbt.putBoolean("immunitytrue", immunitytrue);
			nbt.putBoolean("runningwall", runningwall);
			nbt.putDouble("falling", falling);
			nbt.putDouble("maxfall", maxfall);
			nbt.putDouble("maxfallingbonus", maxfallingbonus);
			nbt.putDouble("magicdirection", magicdirection);
			nbt.putDouble("magicdirection1", magicdirection1);
			nbt.putDouble("magicdirection2", magicdirection2);
			nbt.putDouble("magicdirection3", magicdirection3);
			nbt.putDouble("magicdirection4", magicdirection4);
			nbt.putDouble("magicdirection5", magicdirection5);
			nbt.putDouble("magicdirection6", magicdirection6);
			nbt.putDouble("castingoffset", castingoffset);
			nbt.putDouble("castingoffset1", castingoffset1);
			nbt.putDouble("castingoffset2", castingoffset2);
			nbt.putDouble("castingoffset3", castingoffset3);
			nbt.putDouble("castingoffset4", castingoffset4);
			nbt.putDouble("castingoffset5", castingoffset5);
			nbt.putDouble("castingoffset6", castingoffset6);
			nbt.putDouble("guidedmagic", guidedmagic);
			nbt.putDouble("guidedmagic1", guidedmagic1);
			nbt.putDouble("guidedmagic2", guidedmagic2);
			nbt.putDouble("guidedmagic3", guidedmagic3);
			nbt.putDouble("guidedmagic4", guidedmagic4);
			nbt.putDouble("guidedmagic5", guidedmagic5);
			nbt.putDouble("guidedmagic6", guidedmagic6);
			nbt.putDouble("areacoverage", areacoverage);
			nbt.putDouble("areacoverage1", areacoverage1);
			nbt.putDouble("areacoverage2", areacoverage2);
			nbt.putDouble("areacoverage3", areacoverage3);
			nbt.putDouble("areacoverage4", areacoverage4);
			nbt.putDouble("areacoverage5", areacoverage5);
			nbt.putDouble("areacoverage6", areacoverage6);
			nbt.putDouble("dash5", dash5);
			nbt.putBoolean("fire", fire);
			nbt.putBoolean("fire1", fire1);
			nbt.putBoolean("fire2", fire2);
			nbt.putBoolean("fire3", fire3);
			nbt.putBoolean("fire4", fire4);
			nbt.putBoolean("fire5", fire5);
			nbt.putBoolean("fire6", fire6);
			nbt.putBoolean("water", water);
			nbt.putBoolean("water1", water1);
			nbt.putBoolean("water2", water2);
			nbt.putBoolean("water3", water3);
			nbt.putBoolean("water4", water4);
			nbt.putBoolean("water5", water5);
			nbt.putBoolean("water6", water6);
			nbt.putDouble("gravity", gravity);
			nbt.putDouble("gravity1", gravity1);
			nbt.putDouble("gravity2", gravity2);
			nbt.putDouble("gravity3", gravity3);
			nbt.putDouble("gravity4", gravity4);
			nbt.putDouble("gravity5", gravity5);
			nbt.putDouble("gravity6", gravity6);
			nbt.putDouble("basespeed", basespeed);
			nbt.putBoolean("joinworldlock", joinworldlock);
			nbt.putDouble("movementforward", movementforward);
			nbt.putDouble("movementbackward", movementbackward);
			nbt.putDouble("movementright", movementright);
			nbt.putDouble("movementleft", movementleft);
			nbt.putDouble("movementup", movementup);
			nbt.putDouble("movementenhance", movementenhance);
			nbt.putBoolean("party", party);
			nbt.putBoolean("partyinvite", partyinvite);
			nbt.putDouble("immunityinvited", immunityinvited);
			nbt.putDouble("immunityinvite", immunityinvite);
			nbt.putDouble("partyrank", partyrank);
			nbt.putString("partyname", partyname);
			nbt.putString("magicname", magicname);
			nbt.putString("magicname1", magicname1);
			nbt.putString("magicname2", magicname2);
			nbt.putString("magicname3", magicname3);
			nbt.putString("magicname4", magicname4);
			nbt.putString("magicname5", magicname5);
			nbt.putString("magicname6", magicname6);
			nbt.putString("MagicAttribute", MagicAttribute);
			return nbt;
		}

		@Override
		public void deserializeNBT(HolderLookup.Provider lookupProvider, CompoundTag nbt) {
			mana = nbt.getDouble("mana");
			maxmana = nbt.getDouble("maxmana");
			magicpower = nbt.getDouble("magicpower");
			magicpower1 = nbt.getDouble("magicpower1");
			magicpower2 = nbt.getDouble("magicpower2");
			magicpower3 = nbt.getDouble("magicpower3");
			magicpower4 = nbt.getDouble("magicpower4");
			magicpower5 = nbt.getDouble("magicpower5");
			magicpower6 = nbt.getDouble("magicpower6");
			health = nbt.getDouble("health");
			maxhealth = nbt.getDouble("maxhealth");
			damage = nbt.getDouble("damage");
			armor = nbt.getDouble("armor");
			magicspeed = nbt.getDouble("magicspeed");
			magicspeed1 = nbt.getDouble("magicspeed1");
			magicspeed2 = nbt.getDouble("magicspeed2");
			magicspeed3 = nbt.getDouble("magicspeed3");
			magicspeed4 = nbt.getDouble("magicspeed4");
			magicspeed5 = nbt.getDouble("magicspeed5");
			magicspeed6 = nbt.getDouble("magicspeed6");
			magicsize = nbt.getDouble("magicsize");
			magicsize1 = nbt.getDouble("magicsize1");
			magicsize2 = nbt.getDouble("magicsize2");
			magicsize3 = nbt.getDouble("magicsize3");
			magicsize4 = nbt.getDouble("magicsize4");
			magicsize5 = nbt.getDouble("magicsize5");
			magicsize6 = nbt.getDouble("magicsize6");
			overheat = nbt.getDouble("overheat");
			overheat1 = nbt.getDouble("overheat1");
			overheat2 = nbt.getDouble("overheat2");
			overheat3 = nbt.getDouble("overheat3");
			overheat4 = nbt.getDouble("overheat4");
			overheat5 = nbt.getDouble("overheat5");
			overheat6 = nbt.getDouble("overheat6");
			magicstyle = nbt.getDouble("magicstyle");
			magicstyle1 = nbt.getDouble("magicstyle1");
			magicstyle2 = nbt.getDouble("magicstyle2");
			magicstyle3 = nbt.getDouble("magicstyle3");
			magicstyle4 = nbt.getDouble("magicstyle4");
			magicstyle5 = nbt.getDouble("magicstyle5");
			magicstyle6 = nbt.getDouble("magicstyle6");
			MagicMastery = nbt.getDouble("MagicMastery");
			firemagic = nbt.getBoolean("firemagic");
			watermagic = nbt.getBoolean("watermagic");
			UnlockPoints = nbt.getDouble("UnlockPoints");
			spell = nbt.getDouble("spell");
			Piercing = nbt.getDouble("Piercing");
			Piercing1 = nbt.getDouble("Piercing1");
			Piercing2 = nbt.getDouble("Piercing2");
			Piercing3 = nbt.getDouble("Piercing3");
			Piercing4 = nbt.getDouble("Piercing4");
			Piercing5 = nbt.getDouble("Piercing5");
			Piercing6 = nbt.getDouble("Piercing6");
			Tracking = nbt.getDouble("Tracking");
			Tracking1 = nbt.getDouble("Tracking1");
			Tracking2 = nbt.getDouble("Tracking2");
			Tracking3 = nbt.getDouble("Tracking3");
			Tracking4 = nbt.getDouble("Tracking4");
			Tracking5 = nbt.getDouble("Tracking5");
			Tracking6 = nbt.getDouble("Tracking6");
			MagicShape = nbt.getDouble("MagicShape");
			MagicShape1 = nbt.getDouble("MagicShape1");
			MagicShape2 = nbt.getDouble("MagicShape2");
			MagicShape3 = nbt.getDouble("MagicShape3");
			MagicShape4 = nbt.getDouble("MagicShape4");
			MagicShape5 = nbt.getDouble("MagicShape5");
			MagicShape6 = nbt.getDouble("MagicShape6");
			MagicFollowSetting = nbt.getDouble("MagicFollowSetting");
			MagicFollowSetting1 = nbt.getDouble("MagicFollowSetting1");
			MagicFollowSetting2 = nbt.getDouble("MagicFollowSetting2");
			MagicFollowSetting3 = nbt.getDouble("MagicFollowSetting3");
			MagicFollowSetting4 = nbt.getDouble("MagicFollowSetting4");
			MagicFollowSetting5 = nbt.getDouble("MagicFollowSetting5");
			MagicFollowSetting6 = nbt.getDouble("MagicFollowSetting6");
			SelectionMultiplier = nbt.getDouble("SelectionMultiplier");
			MagicDuration = nbt.getDouble("MagicDuration");
			MagicDuration1 = nbt.getDouble("MagicDuration1");
			MagicDuration2 = nbt.getDouble("MagicDuration2");
			MagicDuration3 = nbt.getDouble("MagicDuration3");
			MagicDuration4 = nbt.getDouble("MagicDuration4");
			MagicDuration5 = nbt.getDouble("MagicDuration5");
			MagicDuration6 = nbt.getDouble("MagicDuration6");
			MultiCast = nbt.getDouble("MultiCast");
			MultiCast1 = nbt.getDouble("MultiCast1");
			MultiCast2 = nbt.getDouble("MultiCast2");
			MultiCast3 = nbt.getDouble("MultiCast3");
			MultiCast4 = nbt.getDouble("MultiCast4");
			MultiCast5 = nbt.getDouble("MultiCast5");
			MultiCast6 = nbt.getDouble("MultiCast6");
			magicaffinity = nbt.getDouble("magicaffinity");
			magicaffinityselected = nbt.getDouble("magicaffinityselected");
			magicaffinity1 = nbt.getDouble("magicaffinity1");
			magicaffinity2 = nbt.getDouble("magicaffinity2");
			magicaffinity3 = nbt.getDouble("magicaffinity3");
			magicaffinity4 = nbt.getDouble("magicaffinity4");
			magicaffinity5 = nbt.getDouble("magicaffinity5");
			magicaffinity6 = nbt.getDouble("magicaffinity6");
			Stamina = nbt.getDouble("Stamina");
			MaxStamina = nbt.getDouble("MaxStamina");
			Dash = nbt.getDouble("Dash");
			Dash2 = nbt.getDouble("Dash2");
			Dash3 = nbt.getDouble("Dash3");
			Dash4 = nbt.getDouble("Dash4");
			Sprint = nbt.getDouble("Sprint");
			MagicCost = nbt.getDouble("MagicCost");
			MagicCost2 = nbt.getDouble("MagicCost2");
			chargeup = nbt.getBoolean("chargeup");
			notenoughmana = nbt.getDouble("notenoughmana");
			wallrunning = nbt.getDouble("wallrunning");
			wallside = nbt.getDouble("wallside");
			immunity = nbt.getDouble("immunity");
			immunitytrue = nbt.getBoolean("immunitytrue");
			runningwall = nbt.getBoolean("runningwall");
			falling = nbt.getDouble("falling");
			maxfall = nbt.getDouble("maxfall");
			maxfallingbonus = nbt.getDouble("maxfallingbonus");
			magicdirection = nbt.getDouble("magicdirection");
			magicdirection1 = nbt.getDouble("magicdirection1");
			magicdirection2 = nbt.getDouble("magicdirection2");
			magicdirection3 = nbt.getDouble("magicdirection3");
			magicdirection4 = nbt.getDouble("magicdirection4");
			magicdirection5 = nbt.getDouble("magicdirection5");
			magicdirection6 = nbt.getDouble("magicdirection6");
			castingoffset = nbt.getDouble("castingoffset");
			castingoffset1 = nbt.getDouble("castingoffset1");
			castingoffset2 = nbt.getDouble("castingoffset2");
			castingoffset3 = nbt.getDouble("castingoffset3");
			castingoffset4 = nbt.getDouble("castingoffset4");
			castingoffset5 = nbt.getDouble("castingoffset5");
			castingoffset6 = nbt.getDouble("castingoffset6");
			guidedmagic = nbt.getDouble("guidedmagic");
			guidedmagic1 = nbt.getDouble("guidedmagic1");
			guidedmagic2 = nbt.getDouble("guidedmagic2");
			guidedmagic3 = nbt.getDouble("guidedmagic3");
			guidedmagic4 = nbt.getDouble("guidedmagic4");
			guidedmagic5 = nbt.getDouble("guidedmagic5");
			guidedmagic6 = nbt.getDouble("guidedmagic6");
			areacoverage = nbt.getDouble("areacoverage");
			areacoverage1 = nbt.getDouble("areacoverage1");
			areacoverage2 = nbt.getDouble("areacoverage2");
			areacoverage3 = nbt.getDouble("areacoverage3");
			areacoverage4 = nbt.getDouble("areacoverage4");
			areacoverage5 = nbt.getDouble("areacoverage5");
			areacoverage6 = nbt.getDouble("areacoverage6");
			dash5 = nbt.getDouble("dash5");
			fire = nbt.getBoolean("fire");
			fire1 = nbt.getBoolean("fire1");
			fire2 = nbt.getBoolean("fire2");
			fire3 = nbt.getBoolean("fire3");
			fire4 = nbt.getBoolean("fire4");
			fire5 = nbt.getBoolean("fire5");
			fire6 = nbt.getBoolean("fire6");
			water = nbt.getBoolean("water");
			water1 = nbt.getBoolean("water1");
			water2 = nbt.getBoolean("water2");
			water3 = nbt.getBoolean("water3");
			water4 = nbt.getBoolean("water4");
			water5 = nbt.getBoolean("water5");
			water6 = nbt.getBoolean("water6");
			gravity = nbt.getDouble("gravity");
			gravity1 = nbt.getDouble("gravity1");
			gravity2 = nbt.getDouble("gravity2");
			gravity3 = nbt.getDouble("gravity3");
			gravity4 = nbt.getDouble("gravity4");
			gravity5 = nbt.getDouble("gravity5");
			gravity6 = nbt.getDouble("gravity6");
			basespeed = nbt.getDouble("basespeed");
			joinworldlock = nbt.getBoolean("joinworldlock");
			movementforward = nbt.getDouble("movementforward");
			movementbackward = nbt.getDouble("movementbackward");
			movementright = nbt.getDouble("movementright");
			movementleft = nbt.getDouble("movementleft");
			movementup = nbt.getDouble("movementup");
			movementenhance = nbt.getDouble("movementenhance");
			party = nbt.getBoolean("party");
			partyinvite = nbt.getBoolean("partyinvite");
			immunityinvited = nbt.getDouble("immunityinvited");
			immunityinvite = nbt.getDouble("immunityinvite");
			partyrank = nbt.getDouble("partyrank");
			partyname = nbt.getString("partyname");
			magicname = nbt.getString("magicname");
			magicname1 = nbt.getString("magicname1");
			magicname2 = nbt.getString("magicname2");
			magicname3 = nbt.getString("magicname3");
			magicname4 = nbt.getString("magicname4");
			magicname5 = nbt.getString("magicname5");
			magicname6 = nbt.getString("magicname6");
			MagicAttribute = nbt.getString("MagicAttribute");
		}

		public void syncPlayerVariables(Entity entity) {
			if (entity instanceof ServerPlayer serverPlayer)
				PacketDistributor.sendToPlayer(serverPlayer, new PlayerVariablesSyncMessage(this));
		}
	}

	public record PlayerVariablesSyncMessage(PlayerVariables data) implements CustomPacketPayload {
		public static final Type<PlayerVariablesSyncMessage> TYPE = new Type<>(ResourceLocation.fromNamespaceAndPath(DreamsOfDivinityMod.MODID, "player_variables_sync"));
		public static final StreamCodec<RegistryFriendlyByteBuf, PlayerVariablesSyncMessage> STREAM_CODEC = StreamCodec
				.of((RegistryFriendlyByteBuf buffer, PlayerVariablesSyncMessage message) -> buffer.writeNbt(message.data().serializeNBT(buffer.registryAccess())), (RegistryFriendlyByteBuf buffer) -> {
					PlayerVariablesSyncMessage message = new PlayerVariablesSyncMessage(new PlayerVariables());
					message.data.deserializeNBT(buffer.registryAccess(), buffer.readNbt());
					return message;
				});

		@Override
		public Type<PlayerVariablesSyncMessage> type() {
			return TYPE;
		}

		public static void handleData(final PlayerVariablesSyncMessage message, final IPayloadContext context) {
			if (context.flow() == PacketFlow.CLIENTBOUND && message.data != null) {
				context.enqueueWork(() -> context.player().getData(PLAYER_VARIABLES).deserializeNBT(context.player().registryAccess(), message.data.serializeNBT(context.player().registryAccess()))).exceptionally(e -> {
					context.connection().disconnect(Component.literal(e.getMessage()));
					return null;
				});
			}
		}
	}
}